---
abstract: 'A libzmq 4.x wrapper for Perl'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  Devel::CheckLib: 0.4
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
  Test::Fatal: 0
  Test::More: 0.98
  Test::Requires: 0
  Test::TCP: 1.08
configure_requires:
  Devel::CheckLib: 0.4
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
  ExtUtils::ParseXS: 3.18
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ZMQ-LibZMQ4
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Task::Weaken: 0
  XSLoader: 0.02
  ZMQ::Constants: 0
resources:
  bugtracker: https://github.com/lestrrat/p5-ZMQ/issues
  homepage: https://github.com/lestrrat/p5-ZMQ
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lestrrat/p5-ZMQ.git
version: 0.01
